# Generated by Django 2.0.4 on 2020-07-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='status',
            new_name='aprovado',
        ),
    ]
