# Generated by Django 2.0.4 on 2020-07-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='comentario',
            new_name='avaliacao',
        ),
    ]
